export const InitCustomerInfoState={
    first_name:{
        value:'',
        error:null
    },
    last_name:{
        value:'',
        error:null
    },
    company_name:{
        value:'',
        error:null
    },
    street_address:{
        value:'',
        error:null
    },
    apartment_suit_unit:{
        value:'',
        error:null
    },
    suburb:{
        value:'',
        error:null
    },
    state:{
        value:'',
        error:null
    },
    postcode:{
        value:'',
        error:null
    },
    phone:{
        value:'',
        error:null
    },
    mobile:{
        value:'',
        error:''
    },
    country:{
        value:'',
        error:''
    },
    dial_code:{
        value:'',
        error:''
    },
    email_address:{
        value:'',
        error:null
    },
    notes:{
        value:'',
        error:null
    },
    card_type:{
        value:'',
        error:null
    },
    c_card_number:{
        value:'',
        error:null
    },
    c_card_name:{
        value:'',
        error:null
    },
    c_expiry_date:{
        value:'',
        error:null
    },
    c_cvc:{
        value:'',
        error:null
    },
    diff_address:{
        value:false
    },
    shipping:{
        value:'shipping'
    },
    term_agreement:{
        value:false,
        error:null
    }

}

