services:
  nodejs_app1:
    image: mynodejs
    ports:
      - 3001:3000
    networks:
      custom_net:
        ipv4_address: 172.18.1.3
  nodejs_app2:
    image: mynodejs
    expose:
      - 3000
    networks:
      custom_net:
        ipv4_address: 172.18.1.4
  nodejs_app3:
    image: mynodejs
    expose:
      - 3000
    networks:
      custom_net:
        ipv4_address: 172.18.1.5
  nodejs_app4:
    image: mynodejs
    expose:
      - 3000
    networks:
      custom_net:
        ipv4_address: 172.18.1.6
  ng_reverse_proxy: 
    image: mynginx
    restart: unless-stopped
    depends_on:
      - nodejs_app1
      - nodejs_app2
      - nodejs_app3
      - nodejs_app4
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "app.com:172.18.1.7"
    networks:
      custom_net:
        ipv4_address: 172.18.1.7
networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24