version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mongodb:/data/db
      - ./init.d/init.js:/docker-entrypoint-initdb.d/init.js:ro
  mongo-seed:
    env_file:
      - .env
    build:
      context: ./seed
      dockerfile: Dockerfile
      args:
        - DATABASE_URI=$DATABASE_URI
        - USERNAME=$MONGO_INITDB_ROOT_USERNAME
        - PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - mongo-express
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  mongodb: