services:
  my-redis-docker-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    depends_on:
      - my-redis-docker-service
    ports:
      - "5540:5540"